# Generated by Django 4.2.21 on 2025-12-02 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户agent信息')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('interrupted', 'Interrupted'), ('failed', 'Failed')], max_length=20)),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户下载记录',
                'verbose_name_plural': '用户下载记录',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(max_length=100, unique=True, verbose_name='上传ID')),
                ('file_md5', models.CharField(db_index=True, max_length=32, verbose_name='文件MD5')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('ext', models.CharField(max_length=10, verbose_name='文件扩展名')),
                ('total_chunks', models.IntegerField(default=0)),
                ('uploaded_chunks', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='文件')),
                ('file_size', models.BigIntegerField(db_index=True, default=0, verbose_name='文件大小(字节)')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文件资料',
                'verbose_name_plural': '文件资料',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserFileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('os', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='操作系统')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.uploadedfile', verbose_name='上传文件')),
            ],
            options={
                'verbose_name': '用户文件',
                'verbose_name_plural': '用户文件',
                'ordering': ['-create_time'],
            },
        ),
    ]
