# Generated by Django 4.2.21 on 2025-12-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#1890ff', max_length=7, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文件标签',
                'verbose_name_plural': '文件标签',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='acodec_type',
            field=models.CharField(default='', max_length=10, verbose_name='音频编码'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='ar_sample_rate',
            field=models.BigIntegerField(default=0, null=True, verbose_name='音频采样率'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='audio_bitrate',
            field=models.BigIntegerField(default=0, null=True, verbose_name='音频码率'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='bitrate',
            field=models.BigIntegerField(default=0, null=True, verbose_name='视频码率'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='duration',
            field=models.FloatField(default=0, max_length=20, null=True, verbose_name='时长'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='fps',
            field=models.FloatField(default=0, max_length=5, null=True, verbose_name='帧率'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='height',
            field=models.FloatField(default=0, max_length=5, null=True, verbose_name='高度'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='vcodec_type',
            field=models.CharField(default='', max_length=10, verbose_name='视频编码'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='width',
            field=models.FloatField(default=0, max_length=5, null=True, verbose_name='宽度'),
        ),
        migrations.AddField(
            model_name='userfileaccess',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='文件描述'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='file.filetag', verbose_name='标签'),
        ),
    ]
