# Generated by Django 4.2.21 on 2025-12-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_filetag_uploadedfile_acodec_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='acodec_type',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='音频编码'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='download_count',
            field=models.IntegerField(default=0, null=True, verbose_name='下载次数'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='vcodec_type',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='视频编码'),
        ),
        migrations.AlterField(
            model_name='userfileaccess',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='素材描述'),
        ),
    ]
