# Generated by Django 4.2.21 on 2025-12-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_alter_uploadedfile_acodec_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfileaccess',
            options={'ordering': ['-create_time'], 'verbose_name': '用户可访问文件', 'verbose_name_plural': '用户可访问文件'},
        ),
    ]
