"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from datetime import timedelta
from email.policy import default
from pathlib import Path
import sys
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1$%am(yzb%oovcp=addhpy7faf)^se69h!$!g&4pehylk7or0o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda x: x.split(',')) or ['*']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'channels',

    'django_db_geventpool',  # 可选，部分版本需要

    'captcha',
    "django_filters",
    "rest_framework",
    "corsheaders",  # 注册跨域app
    'rest_framework_simplejwt',
    'django_celery_beat',
    'user',
    'file',
    'vpn',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # 跨域中间件
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user.middleware.ApiLoggingMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


if sys.platform == 'linux':
    # redis 配置
    REDIS_HOST = config('REDIS_HOST')
    REDIS_PASSWORD = config('REDIS_PASSWORD')
    REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)

    # REDIS_LOCATION = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
    REDIS_LOCATION = f"redis://{REDIS_HOST}:{REDIS_PORT}"

    # DATABASES = {
    #     'default': {
    #
    #         'ENGINE': 'django.db.backends.mysql',
    #         'NAME': 'vue3_comany',
    #         'USER': 'vue3_comany',
    #         'PASSWORD': 'ENy2JcJA6tyi5D2m',
    #         'HOST': '127.0.0.1',
    #         'PORT': 3306,
    #         'CONN_MAX_AGE': 60 * 60 * 2,
    #         # 以下解决
    #         'OPTIONS': {
    #             "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
    #             'charset': 'utf8mb4',
    #         }
    #
    #     }
    # }

    # pip install psycopg2-binary  # PostgreSQL 驱动
    # pip install django-db-connection-pool  # 连接池

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',  # 标准后端 不能配置OPTIONS
            # 'ENGINE': 'dj_db_conn_pool.backends.postgresql',  # 使用连接池配置`
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST'),
            'PORT': config('DB_PORT'),
            'CONN_MAX_AGE': config('CONN_MAX_AGE', default=7200, cast=int),
            'OPTIONS': {
                'connect_timeout': 15,
                'options': '-c statement_timeout=30000',
                'keepalives': 1,  # 启用 TCP Keepalive
                'keepalives_idle': 30,  # 空闲 30 秒后发送探测包
            },

            # 'OPTIONS': {
            #     'MAX_CONNS': 20,  # 连接池大小 现在可以用，因为 ENGINE 是 django_db_geventpool
            #     'REUSE_CONNS': 10, # 连接复用
            # },

            # 'POOL_OPTIONS': {
            #     'POOL_SIZE': 10,  # 主连接池大小
            #     'MAX_OVERFLOW': 5, # 最大溢出连接数（临时连接）
            #     'RECYCLE': 600,  # 600 秒（10分钟）连接回收时间（秒）
            #     'TIMEOUT': 30,  # 30 秒 获取连接的最大等待时间（秒
            # }
        }
    }


else:
    # redis 配置
    REDIS_HOST = '127.0.0.1'
    REDIS_PASSWORD = 'dayue123456'
    REDIS_PORT = 6379
    REDIS_LOCATION = f"redis://{REDIS_HOST}:{REDIS_PORT}"

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

# 素材上传配置
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # 保留默认后端
    'user.authentication.EnhancedAuthBackend',  # 自定义认证后端

]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60 * 4),  # token有效时长4个小时
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# ================================================= #
# ******************* 跨域的配置 ******************* #
# ================================================= #

# 允许所有来源（仅用于开发环境）
# CORS_ALLOW_ALL_ORIGINS = True

# 或者指定允许的前端地址（推荐用于生产环境）
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # 前端地址
    "http://192.168.20.33:5173",  # 前端地址
    "http://digit.first-iq.com:10870",  # 前端地址
    "http://digit.first-iq.com:10871",  # 前端地址
]

# 指定允许的后端地址（推荐用于生产环境）
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",  # 前端地址
    "http://192.168.20.33:5173",  # 前端地址
    "http://digit.first-iq.com:10870",
    "http://digit.first-iq.com:10871",  # 前端地址
    # Add other trusted origins if needed
]

# 暴露自定义头,否则前端无法获取自定义头
CORS_EXPOSE_HEADERS = ['Captcha-Key', 'Content-Disposition']

# ================================================= #
# ***************** chaptcha配置 ******************* #
# ================================================= #

# Redis配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_LOCATION}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 验证码配置
CAPTCHA_TIMEOUT = 300  # 超时(5分钟)
CAPTCHA_FONT_PATH = BASE_DIR / 'static' / 'fonts' / 'arial.ttf'
CAPTCHA_FONT_SIZE = 30

CAPTCHA_IMAGE_SIZE = (160, 43)  # 图片尺寸
CAPTCHA_LENGTH = 4  # 设置字符个数
# 输出格式：输入框， 验证码图片， 隐藏域
CAPTCHA_OUTPUT_FORMAT = '%(text_field)s %(image)s %(hidden_field)s'
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_null',
                           # 'captcha.helpers.noise_arcs',  # 线
                           'captcha.helpers.noise_dots',  # 点
                           )
# 随机字符验证码
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'
# 简单数学计算
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
# 单词
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.word_challenge'


# ================================================= #
# ******************* 邮箱配置 ******************* #
# ================================================= #
# smtp后端,默认配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 控制台后端开发时使用
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)
# EMAIL_FROM_EMAIL = config('EMAIL_FROM_EMAIL')
EMAIL_SUBJECT_PREFIX = config('EMAIL_SUBJECT_PREFIX')
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=300, cast=int)  # 超时(5分钟)

# pip install django-simple-captcha django-redis aliyun-python-sdk-core aliyun-python-sdk-dysmsapi

# 阿里云短信配置
SMS_CONFIG = {
    'ACCESS_KEY_ID': 'your-access-key-id',
    'ACCESS_KEY_SECRET': 'your-access-key-secret',
    'SIGN_NAME': 'your-sign-name',
    'TEMPLATE_CODE': 'your-template-code',
    'REGION': 'cn-hangzhou'
}

# 安全配置
MAX_LOGIN_ATTEMPTS = 3  # 登录失败允许的最大尝试次数
LOGIN_ATTEMPT_TIMEOUT = 60 * 15  # 15分钟计数周期
API_SECRET_KEY = 'DEEF0F5ED06AC32E3E06A7E2C5587DB8'

# celery配置
"""
在 Windows 上运行 Celery 需要特殊处理：
# 安装 eventlet 支持
pip install eventlet
# 使用 eventlet 池运行
celery -A backend worker -l info --pool=eventlet
"""

# Celery 配置
CELERY_BROKER_URL = f'{REDIS_LOCATION}'
CELERY_RESULT_BACKEND = f'{REDIS_LOCATION}'
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

CELERYD_HIJACK_ROOT_LOGGER = False
CELERYBEAT_LOG_LEVEL = 'INFO'

# 添加这些关键配置
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ENABLE_UTC = False  # 设置False

CELERY_REDIS_MAX_CONNECTIONS = 20
BROKER_POOL_LIMIT = 10

# 增加以下配置
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,  # 任务可见性超时(秒)
    'socket_keepalive': True,  # 保持 TCP 连接活跃
    'retry_policy': {
        'interval_start': 0,
        'interval_max': 1,
        'max_retries': 3,
    }
}

# 防止任务堆积和长时间运行
CELERY_TASK_TIME_LIMIT = 3600  # 1小时
CELERY_TASK_SOFT_TIME_LIMIT = 3000  # 50分钟 软性超时
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # 防止任务堆积

# Redis 心跳配置 增加 Broker 心跳频率
CELERY_BROKER_HEARTBEAT = 180  # 每 3 分钟发送心跳
CELERY_BROKER_CONNECTION_TIMEOUT = 30  # 连接超时30秒

# 设为0，存储结果永不过期
CELERY_RESULT_EXPIRES = 0
# CELERY_RESULT_EXPIRES = 86400  # 1天后过期
CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24  # 后端存储的任务超过一天时，自动删除数据库中的任务数据，单位秒
CELERY_MAX_TASKS_PER_CHILD = 1000  # 每个worker执行1000次任务后，自动重启worker，防止任务占用太多内存导致内存泄漏
# DJANGO_CELERY_BEAT_TZ_AWARE = False


CELERYD_LOG_FILE = "/var/log/celery/vpn-celery.log"

# # 设置定时任务
# CELERY_BEAT_SCHEDULE = {
#     'monitor-vpn': {
#         'task': 'vpn.tasks.monitor_vpn_task',
#         'schedule': 5.0,  # 每300秒
#         'args': (),
#     },
# }


# 确保会话引擎可用
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 或 'django.contrib.sessions.backends.cache'

# 检查 Cookie 设置（关键！）
SESSION_COOKIE_SECURE = False  # 本地开发时设为 False，HTTPS 生产环境应为 True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # 或 None
CSRF_COOKIE_SECURE = False  # 与 SESSION_COOKIE_SECURE 同步

BASE_URL = 'http://digit.first-iq.com:10870/'

# pip install gunicorn gevent
# gunicorn --bind 0.0.0.0:8000 backend.wsgi:application


API_LOG_ENABLE = True
# API_LOG_METHODS = 'ALL' # ['POST', 'DELETE']
API_LOG_METHODS = ["POST", "UPDATE", "DELETE", "PUT", 'PATCH']  # ['POST', 'DELETE']
API_MODEL_MAP = {
    "/user/api/profile/": "个人资料",
    "/user/api/auth/login/": "登录",
    "/user/api/upload/avatar/": "上传头像",
    "/user/api/change/password/": "修改密码",
    "/file/api/upload/init/": "素材上传",
    "/file/api/upload/complete/": "素材上传",
    "/file/api/download/": "素材下载",
    "/file/api/": "素材管理",
    "/vpn/api/vpn-accounts/": "账号接口",
    "/vpn/api/": "VPN管理"
}
EXLUDE_API_LOG = [
    "/file/api/upload/chunk/"  # 素材上传中
]
API_METHOD_MAP = {
    'GET': '查询',
    'POST': '新建',
    'PUT': '更新',
    'DELETE': '删除',
    'PATCH': '修改',
}

REGION_CODE_TO_NAME = {
    'JP': '日本',
    'SG': '新加坡',
    'TWN': '台湾',
    'KOR': '韩国',
    'IDN': '印尼',
    'MAS': '马来西亚',
    'THA': '泰国',
    'UK': '英国',
    'GER': '德国',
    'US': '美国',
    'VN': '越南',
    'PH': '菲律宾',
    # ... 其他区域
}

REGION_CODE_TO_ENGLISH = {
    'JP': 'Japan',
    'SG': 'Singapore',
    'TWN': 'Taiwan',
    'KOR': 'South Korea',
    'IDN': 'Indonesia',
    'MAS': 'Malaysia',
    'THA': 'Thailand',
    'UK': 'United Kingdom',
    'GER': 'Germany',
    'US': 'United States of America',
    'VN': 'Vietnam',
    'PH': 'Philippines',
    # ... 其他区域
}
