# Generated by Django 4.2.21 on 2025-12-02 05:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='用户名')),
                ('real_name', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='真实姓名')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='手机号')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否是超级管理员')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否是员工')),
                ('require_captcha', models.BooleanField(default=False, verbose_name='是否需要验证码')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-create_time'],
                'permissions': [('add_user', '可以添加用户'), ('view_user', '可以查看用户'), ('change_user', '可以修改用户'), ('delete_user', '可以删除用户'), ('assign_role', '可以分配角色'), ('assign_department', '可以分配部门')],
                'default_permissions': [],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('expire_time', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('code', models.CharField(max_length=50, verbose_name='菜单编码')),
                ('type', models.IntegerField(choices=[(0, '目录'), (1, '菜单'), (2, '按钮')], default=0, verbose_name='菜单类型')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, max_length=200, null=True, verbose_name='组件路径')),
                ('permission', models.CharField(blank=True, max_length=200, null=True, verbose_name='权限标识')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='商品编码')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成本')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.IntegerField(choices=[(0, '下架'), (1, '上架')], default=1, verbose_name='状态')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='角色编码')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('menus', models.ManyToManyField(blank=True, related_name='roles', to='user.menu', verbose_name='菜单权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y%m%d/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='简介')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='地址')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部门名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='部门编码')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.department', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='user.role', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('request_modular', models.CharField(blank=True, db_index=True, help_text='请求模块', max_length=64, null=True, verbose_name='请求模块')),
                ('request_path', models.CharField(blank=True, help_text='请求地址', max_length=400, null=True, verbose_name='请求地址')),
                ('request_body', models.TextField(blank=True, help_text='请求参数', null=True, verbose_name='请求参数')),
                ('request_method', models.CharField(blank=True, db_index=True, help_text='请求方式', max_length=8, null=True, verbose_name='请求方式')),
                ('request_msg', models.TextField(blank=True, help_text='操作说明', null=True, verbose_name='操作说明')),
                ('request_ip', models.CharField(blank=True, db_index=True, help_text='请求ip地址', max_length=50, null=True, verbose_name='请求ip地址')),
                ('request_browser', models.CharField(blank=True, db_index=True, help_text='请求浏览器', max_length=64, null=True, verbose_name='请求浏览器')),
                ('response_code', models.CharField(blank=True, db_index=True, help_text='响应状态码', max_length=64, null=True, verbose_name='响应状态码')),
                ('request_os', models.CharField(blank=True, db_index=True, help_text='操作系统', max_length=64, null=True, verbose_name='操作系统')),
                ('json_result', models.TextField(blank=True, help_text='返回信息', null=True, verbose_name='返回信息')),
                ('status', models.BooleanField(db_index=True, default=False, help_text='响应状态', verbose_name='响应状态')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_log',
                'ordering': ('-create_time',),
                'indexes': [models.Index(fields=['create_time'], name='operation_l_create__33a8d5_idx'), models.Index(fields=['creator', 'create_time'], name='operation_l_creator_058bee_idx'), models.Index(fields=['status', 'create_time'], name='operation_l_status_df2945_idx'), models.Index(fields=['request_modular', 'create_time'], name='operation_l_request_7a0f02_idx'), models.Index(fields=['creator', 'status'], name='operation_l_creator_c5f26c_idx'), models.Index(fields=['creator', 'create_time', 'status'], name='operation_l_creator_817c22_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('username', models.CharField(blank=True, db_index=True, help_text='登录用户名', max_length=32, null=True, verbose_name='登录用户名')),
                ('ip', models.CharField(blank=True, db_index=True, help_text='登录ip', max_length=50, null=True, verbose_name='登录ip')),
                ('agent', models.TextField(blank=True, help_text='agent信息', null=True, verbose_name='agent信息')),
                ('browser', models.CharField(blank=True, db_index=True, help_text='浏览器名', max_length=200, null=True, verbose_name='浏览器名')),
                ('os', models.CharField(blank=True, db_index=True, help_text='操作系统', max_length=200, null=True, verbose_name='操作系统')),
                ('continent', models.CharField(blank=True, db_index=True, help_text='洲', max_length=50, null=True, verbose_name='州')),
                ('country', models.CharField(blank=True, db_index=True, help_text='国家', max_length=50, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, db_index=True, help_text='省份', max_length=50, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, db_index=True, help_text='城市', max_length=50, null=True, verbose_name='城市')),
                ('district', models.CharField(blank=True, db_index=True, help_text='县区', max_length=50, null=True, verbose_name='县区')),
                ('isp', models.CharField(blank=True, db_index=True, help_text='运营商', max_length=50, null=True, verbose_name='运营商')),
                ('area_code', models.CharField(blank=True, db_index=True, help_text='区域代码', max_length=50, null=True, verbose_name='区域代码')),
                ('country_english', models.CharField(blank=True, db_index=True, help_text='英文全称', max_length=50, null=True, verbose_name='英文全称')),
                ('country_code', models.CharField(blank=True, db_index=True, help_text='简称', max_length=50, null=True, verbose_name='简称')),
                ('longitude', models.CharField(blank=True, help_text='经度', max_length=50, null=True, verbose_name='经度')),
                ('latitude', models.CharField(blank=True, help_text='纬度', max_length=50, null=True, verbose_name='纬度')),
                ('login_type', models.IntegerField(choices=[(1, '普通登录'), (2, '扫码登录')], db_index=True, default=1, help_text='登录类型', verbose_name='登录类型')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'login_log',
                'ordering': ('-create_time',),
                'indexes': [models.Index(fields=['create_time'], name='login_log_create__aac598_idx'), models.Index(fields=['creator', 'create_time'], name='login_log_creator_680638_idx'), models.Index(fields=['username', 'create_time'], name='login_log_usernam_ed5fb5_idx'), models.Index(fields=['ip', 'create_time'], name='login_log_ip_5a1a64_idx'), models.Index(fields=['os', 'create_time'], name='login_log_os_7540bf_idx'), models.Index(fields=['country', 'province', 'city'], name='login_log_country_551ab9_idx'), models.Index(fields=['login_type', 'create_time'], name='login_log_login_t_f19502_idx'), models.Index(fields=['creator', 'create_time', 'username'], name='login_log_creator_77e937_idx'), models.Index(fields=['ip', 'create_time', 'username'], name='login_log_ip_738067_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='user_user_usernam_6d9439_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['real_name'], name='user_user_real_na_3ab4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['mobile'], name='user_user_mobile_94140f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='user_user_is_acti_829fed_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department'], name='user_user_departm_89e822_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'is_active'], name='user_user_usernam_11120c_idx'),
        ),
    ]
