# Generated by Django 4.2.21 on 2025-12-02 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DyvpnAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vpn_account', models.CharField(default='', max_length=50, null=True, unique=True)),
                ('vpn_pwd', models.CharField(default='', max_length=50, null=True)),
                ('nickname', models.CharField(default='', max_length=50, null=True)),
                ('used', models.BooleanField(default=True, null=True, verbose_name='使用状态')),
                ('is_delete', models.BooleanField(default=False, null=True, verbose_name='删除状态')),
                ('online', models.BooleanField(default=False, null=True, verbose_name='在线状态')),
                ('count', models.IntegerField(default=1, null=True)),
                ('industry_type', models.IntegerField(choices=[(1, '个人'), (2, '企业'), (3, '政府'), (4, '教育'), (5, '金融'), (6, '医疗'), (7, '保险'), (8, '科技'), (9, '游戏'), (10, '旅游'), (11, '互联网'), (12, '其他')], db_index=True, default=1, null=True, verbose_name='行业类型')),
                ('recommender', models.CharField(default='', max_length=50, null=True, verbose_name='推荐人')),
                ('organization_name', models.CharField(default='', max_length=50, null=True, verbose_name='机构名称')),
                ('organization_address', models.CharField(default='', max_length=50, null=True, verbose_name='机构地址')),
                ('contact', models.CharField(default='', max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(default='', max_length=50, null=True, verbose_name='联系方式')),
                ('expire_time', models.DateTimeField(null=True, verbose_name='到期时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('remark', models.TextField(default='', null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '账号',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DyvpnDeviceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(default='', max_length=50, null=True, verbose_name='设备名称')),
                ('device_number', models.CharField(default='', max_length=50, null=True, verbose_name='设备编号')),
                ('device_type', models.IntegerField(choices=[(1, '路由器'), (2, '交换机'), (3, '防火墙'), (4, 'VPN'), (5, '服务器'), (6, 'PC'), (7, '移动终端'), (8, '其他')], db_index=True, default=3, null=True, verbose_name='设备类型')),
                ('device_desc', models.TextField(default='', null=True, verbose_name='设备描述')),
                ('serial_number', models.CharField(default='', max_length=50, null=True, verbose_name='设备序列号')),
                ('mac_address', models.CharField(default='', max_length=50, null=True, verbose_name='MAC地址')),
                ('vpn_server', models.CharField(default='', max_length=200, null=True, verbose_name='VPN服务器地址')),
                ('route_url', models.CharField(default='', max_length=200, null=True, verbose_name='路由地址')),
                ('account', models.CharField(default='', max_length=50, null=True, verbose_name='管理员账号')),
                ('password', models.CharField(default='', max_length=50, null=True, verbose_name='管理员密码')),
                ('cookie', models.TextField(default='', null=True)),
                ('used', models.BooleanField(default=False, null=True, verbose_name='设备状态')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DyvpnRegionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(default='', max_length=50, null=True, verbose_name='区域')),
                ('region_code', models.CharField(default='', max_length=50, null=True, verbose_name='区域代码')),
                ('device_count', models.IntegerField(default=1000, null=True, verbose_name='终端数量上限')),
                ('online_num', models.IntegerField(default=0, null=True, verbose_name='当前数量')),
                ('used', models.BooleanField(default=False, null=True, verbose_name='是否可用')),
                ('group_code', models.CharField(default='', max_length=50, null=True, verbose_name='分组代码')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='vpn.dyvpndevicemodel', verbose_name='防火墙设备')),
                ('vpn_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vpn_device', to='vpn.dyvpndevicemodel', verbose_name='VPN设备')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DyvpnMonitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration_secs', models.BigIntegerField(default=0, null=True, verbose_name='在线时长(秒)')),
                ('expiry_secs', models.BigIntegerField(default=0, null=True, verbose_name='到期时间')),
                ('online_time', models.CharField(default='', max_length=50, null=True, verbose_name='在线时长')),
                ('virtual_ip', models.CharField(default='', max_length=50, null=True, verbose_name='虚拟IP')),
                ('login_terminal', models.CharField(default='', max_length=50, null=True, verbose_name='登录终端')),
                ('login_ip', models.CharField(default='', max_length=50, null=True, verbose_name='登录IP')),
                ('in_bytes', models.BigIntegerField(default=0, null=True, verbose_name='下行字节')),
                ('out_bytes', models.BigIntegerField(default=0, null=True, verbose_name='上行字节')),
                ('traffic_vol_bytes', models.BigIntegerField(default=0, null=True, verbose_name='流量字节数')),
                ('down_flow', models.CharField(default='', max_length=100, null=True, verbose_name='下行流量')),
                ('up_flow', models.CharField(default='', max_length=100, null=True, verbose_name='上行流量')),
                ('traffic_vol_flow', models.CharField(default='', max_length=100, null=True, verbose_name='上下行流量')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='退出时间')),
                ('login_time', models.DateTimeField(verbose_name='登录时间')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn.dyvpnaccount', verbose_name='账号')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn.dyvpnregionmodel', verbose_name='区域')),
            ],
            options={
                'verbose_name': 'VPN监控日志',
                'verbose_name_plural': 'VPN监控日志',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AddIndex(
            model_name='dyvpndevicemodel',
            index=models.Index(fields=['device_name'], name='vpn_dyvpnde_device__115e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpndevicemodel',
            index=models.Index(fields=['account'], name='vpn_dyvpnde_account_a76047_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpndevicemodel',
            index=models.Index(fields=['used'], name='vpn_dyvpnde_used_10f376_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpndevicemodel',
            index=models.Index(fields=['device_type'], name='vpn_dyvpnde_device__b3ad76_idx'),
        ),
        migrations.AddField(
            model_name='dyvpnaccount',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn.dyvpndevicemodel', verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='dyvpnaccount',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn.dyvpnregionmodel', verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='dyvpnaccount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='dyvpnregionmodel',
            index=models.Index(fields=['region'], name='vpn_dyvpnre_region_adc49e_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnregionmodel',
            index=models.Index(fields=['region_code'], name='vpn_dyvpnre_region__045c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnregionmodel',
            index=models.Index(fields=['device'], name='vpn_dyvpnre_device__e5d291_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnmonitor',
            index=models.Index(fields=['account'], name='vpn_dyvpnmo_account_533dde_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnmonitor',
            index=models.Index(fields=['login_time'], name='vpn_dyvpnmo_login_t_4b447c_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnmonitor',
            index=models.Index(fields=['logout_time'], name='vpn_dyvpnmo_logout__1be1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnmonitor',
            index=models.Index(fields=['login_time', 'account'], name='vpn_dyvpnmo_login_t_34edce_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnmonitor',
            index=models.Index(fields=['logout_time', 'account'], name='vpn_dyvpnmo_logout__6bc18e_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnmonitor',
            index=models.Index(fields=['account', 'login_time'], name='vpn_dyvpnmo_account_9f4fca_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnmonitor',
            index=models.Index(condition=models.Q(('logout_time__isnull', True)), fields=['logout_time'], name='dyvpn_monitor_online_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnmonitor',
            index=models.Index(fields=['traffic_vol_bytes', 'login_time'], name='vpn_dyvpnmo_traffic_f3682e_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnaccount',
            index=models.Index(fields=['vpn_account'], name='vpn_dyvpnac_vpn_acc_c51052_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnaccount',
            index=models.Index(fields=['nickname'], name='vpn_dyvpnac_nicknam_1fd226_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnaccount',
            index=models.Index(fields=['online'], name='vpn_dyvpnac_online_a31093_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnaccount',
            index=models.Index(fields=['user'], name='vpn_dyvpnac_user_id_d04ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='dyvpnaccount',
            index=models.Index(fields=['region'], name='vpn_dyvpnac_region__a00c16_idx'),
        ),
    ]
